<?php
namespace KeriganSolutions\KMARealtor;

class CustomSearch {

    public function __construct()
    {

    }
    
    public function use()
    {
        if( function_exists('acf_add_local_field_group') ){
            $this->addSearchFields();
        }
    }

    public function addSearchFields()
    {
        acf_add_local_field_group(array(
            'key' => 'group_5cc795714252c',
            'title' => 'Search Fields',
            'fields' => array(
                array(
                    'key' => 'field_5cc795a621979',
                    'label' => 'Keyword',
                    'name' => 'omni',
                    'type' => 'text',
                    'instructions' => 'Address, Area, Zip, MLS#',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5cc798722b852',
                    'label' => 'Area',
                    'name' => 'area',
                    'type' => 'text',
                    'instructions' => 'Area or Sub_Area accepted',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5cc795e52197a',
                    'label' => 'Property Type',
                    'name' => 'property_type',
                    'type' => 'select',
                    'instructions' => 'Select Navica property type',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Any' => 'Any',
                        'AllHomes' => 'All Homes',
                        'AllLand' => 'All Land',
                        'Detached Single Family' => 'Single Family Homes',
                        'MultiUnit' => 'Condos/Townhouses/Multi',
                        'Commercial' => 'Commercial',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5cc79903c2a51',
                    'label' => 'Minimum Price',
                    'name' => 'min_price',
                    'type' => 'number',
                    'instructions' => 'no commas',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24.5',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5cc79934c2a52',
                    'label' => 'Maximum Price',
                    'name' => 'max_price',
                    'type' => 'number',
                    'instructions' => 'no commas',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24.5',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5cc7996a22f2b',
                    'label' => 'Bedrooms',
                    'name' => 'beds',
                    'type' => 'number',
                    'instructions' => '&nbsp;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24.5',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5cc799de22f2c',
                    'label' => 'Bathrooms',
                    'name' => 'baths',
                    'type' => 'number',
                    'instructions' => '&nbsp;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24.5',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5cc79d81100d8',
                    'label' => 'Sqft',
                    'name' => 'sqft',
                    'type' => 'text',
                    'instructions' => '&nbsp;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24.5',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5cc79bf82f2f6',
                    'label' => 'Acreage',
                    'name' => 'acreage',
                    'type' => 'number',
                    'instructions' => '&nbsp;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24.5',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5cc79dd3c843e',
                    'label' => 'Status',
                    'name' => 'status',
                    'type' => 'select',
                    'instructions' => '&nbsp;',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Active|Contingent' => 'Active & Contingent',
                        'Active' => 'Active',
                        'Contingent' => 'Contingent',
                        'Sold/Closed' => 'Sold',
                    ),
                    'default_value' => array(
                        0 => 'Active|Contingent',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5cc7acfbf44b0',
                    'label' => 'Foreclosure',
                    'name' => 'foreclosure',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '12',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_5cc7ad2baac4a',
                    'label' => 'Waterfront',
                    'name' => 'waterfront',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '12',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'template-custom-search.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));
        
    }
}